# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "reduce"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = "2012-12-30"
  s.email = "grosser.michael@gmail.com"
  s.executables = ["reduce"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/reduce",
    "lib/reduce.rb",
    "reduce.gemspec",
    "spec/files/facebox.css",
    "spec/files/facebox.js",
    "spec/files/paintcan.png",
    "spec/files/test.gif",
    "spec/files/wikipedia.html",
    "spec/reduce_spec.rb",
    "spec/spec_helper.rb",
    "vendor/README",
    "vendor/htmlcompressor-1.5.3.jar",
    "vendor/yuicompressor-2.4.6.jar"
  ]
  s.homepage = "http://github.com/grosser/reduce"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Reduce your assets: minify javascript + stylesheets, optimize images lossless"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<["smusher"]>, [">= 0"])
    else
      s.add_dependency(%q<["smusher"]>, [">= 0"])
    end
  else
    s.add_dependency(%q<["smusher"]>, [">= 0"])
  end
end

